config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /en|uk|ru/ do
    root to: 'home#show'
    get 'index.html', to: 'home#show'
    get 'about', to: 'home#about'
    get 'blog-list', to: 'post#index'
    get 'blog-post', to: 'post#show'

    namespace :admin do
      root to: 'home#show'
      resources :posts do
        delete :destroy_image, on: :member
      end
    end
    # devise_for :users,
    #           path_names: {sign_in: 'login',
    #                        sign_out: 'logout',
    #                        password: 'secret',
    #                        sign_up: 'registration'},
    #           controllers: {sessions: 'users/sessions',
    #                         registrations: 'users/registrations',
    #                         passwords: 'users/passwords',
    #                         confirmations: 'users/confirmations',
    #                         unlocks: 'users/unlocks',
    #           }
    devise_for :users, skip: %i[sessions registrations passwords confirmations unlock]
    as :user do
      get 'login.html', to: 'users/sessions#new', as: :new_user_session
      post 'login.html', to: 'users/sessions#create', as: :user_session
      match 'logout.html', to: 'users/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via

      get 'registration.html', to: 'users/registrations#new', as: :new_user_registration
      post 'registration.html', to: 'users/registrations#create', as: :user_registration
      get 'edit-registration.html', to: 'users/registrations#edit', as: :edit_user_registration
      patch 'registration.html', to: 'users/registrations#update', as: :patch_user_registration
      delete 'registration.html', to: 'users/registrations#destroy', as: :delete_user_registration
      delete 'remove-avatar/:id', to: 'users/registrations#destroy_avatar', as: :delete_user_avatar_registration

      get 'recover-password.html', to: 'users/passwords#new', as: :new_user_password
      post 'recover-password.html', to: 'users/passwords#create'
      get 'edit-recover-password.html', to: 'users/passwords#edit', as: :edit_user_password
      patch 'recover-password.html', to: 'users/passwords#update', as: :user_password
      put 'recover-password.html', to: 'users/passwords#update'

      get 'confirmation.html', to: 'users/confirmations#new', as: :new_user_confirmation
      get 'show-confirmation.html', to: 'users/confirmations#show', as: :user_confirmation
      post 'show-confirmation.html', to: 'users/confirmations#create'

      get 'unlock.html', to: 'users/unlocks#new', as: :new_user_unlock
      get 'show-unlock.html', to: 'users/unlocks#show', as: :user_unlock
      post 'show-unlock.html', to: 'users/unlocks#create'
    end

    # match '*a', to: 'admin/errors#not_found', via: :all unless Rails.env.development?
    # match '*a', to: 'admin/errors#not_found', via: :all
  end
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/home_controller.rb
# frozen_string_literal: true

class Admin::HomeController < Admin::BaseController
  def show
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < BaseController
  def show
  end

  def about
  end
end

app/views/home/about.html.slim
.main-wrapper
  article.about-section.py-5
    .container
      h2.title.mb-3 About Me
      p Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.
      figure
        = image_tag "about-me.jpg", title: "",alt:"image", class: "img-fluid"
      h5.mt-5 About The Blog
      p Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam, scelerisque ut, mollis sed, nonummy id, metus.
      h5.mt-5 My Skills and Experiences
      p Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi.
      h5.mt-5 Side Projects
      p Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi.
      figure
        a href="https://made4dev.com"
          = image_tag "promo-banner.jpg", title: "",alt:"image", class: "img-fluid"
  /! //about-section
  section.cta-section.theme-bg-light.py-5
    .container.text-center
      h2.heading Newsletter
      .intro Welcome to my blog. Subscribe and get my latest blog post in your inbox.
      form.signup-form.form-inline.justify-content-center.pt-3
        .form-group
          label.sr-only for="semail"  Your email
          input#semail.form-control.mr-md-1.semail name="semail1" placeholder=("Enter email") type="email" /
        button.btn.btn-primary type="submit"  Subscribe
  /! //container

        /! //main-wrapper

app/views/home/show.html.slim
.main-wrapper
  section.cta-section.theme-bg-light.py-5
    .container.text-center
      - if current_user
        = t('welcome')
        | &nbsp;
        = link_to admin_root_path
          = current_user.email
        p
          = link_to destroy_user_session_path, method: :delete
            = t('devise.custom.log out')
      - else
        = t('welcome')
        | &nbsp;
        = t('devise.custom.guest')
        p
          = link_to new_user_session_path
            = t('devise.custom.log in')
      h2.heading DevBlog - A Blog Template Made For Developers
      .intro Welcome to my blog. Subscribe and get my latest blog post in your inbox.
      form.signup-form.form-inline.justify-content-center.pt-3
        .form-group
          label.sr-only for="semail"  Your email
          input#semail.form-control.mr-md-1.semail name="semail1" placeholder=("Enter email") type="email" /
        button.btn.btn-primary type="submit"  Subscribe
  /! //container
  section.blog-list.px-3.py-5.p-md-5
    .container
      .item.mb-5
        .media
          = image_tag "blog/blog-post-thumb-1.jpg", title: "",alt:"image", class: "mr-3 img-fluid post-thumb d-none d-md-flex"
          .media-body
            h3.title.mb-1
              a href="blog-post.html"  Why Every Developer Should Have A Blog
            .meta.mb-1
              span.date Published 2 days ago
              span.time 5 min read
              span.comment
                a href="#"  8 comments
            .intro Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies...
            a.more-link href="blog-post.html"  Read more →
      /! //media-body
      /! //media
      /! //item
      .item.mb-5
        .media
          = image_tag "blog/blog-post-thumb-2.jpg", title: "",alt:"image", class: "mr-3 img-fluid post-thumb d-none d-md-flex"
          .media-body
            h3.title.mb-1
              a href="blog-post.html"  A Guide to Becoming a Full-Stack Developer
            .meta.mb-1
              span.date Published 3 months ago
              span.time 3 min read
              span.comment
                a href="#"  26 comments
            .intro Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies...
            a.more-link href="blog-post.html"  Read more →
      /! //media-body
      /! //media
      /! //item
      .item.mb-5
        .media
          = image_tag "blog/blog-post-thumb-3.jpg", title: "", alt: "image", class: "mr-3 img-fluid post-thumb d-none d-md-flex"
          .media-body
            h3.title.mb-1
              a href="blog-post.html"  High Performance JavaScript
            .meta.mb-1
              span.date Published 1 month ago
              span.time 8 min read
              span.comment
                a href="#"  12 comments
            .intro Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies...
            a.more-link href="blog-post.html"  Read more →
      /! //media-body
      /! //media
      /! //item
      .item.mb-5
        .media
          = image_tag "blog/blog-post-thumb-4.jpg", title: "", alt: "image", class: "mr-3 img-fluid post-thumb d-none d-md-flex"
          .media-body
            h3.title.mb-1
              a href="blog-post.html"  Top 5 JavaScript Frameworks
            .meta.mb-1
              span.date Published 2 months ago
              span.time 15 min read
              span.comment
                a href="#"  3 comments
            .intro Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies...
            a.more-link href="blog-post.html"  Read more →
      /! //media-body
      /! //media
      /! //item
      .item.mb-5
        .media
          = image_tag "blog/blog-post-thumb-5.jpg", title: "", alt: "image", class: "mr-3 img-fluid post-thumb d-none d-md-flex"
          .media-body
            h3.title.mb-1
              a href="blog-post.html"  Learn React in 24 Hours
            .meta.mb-1
              span.date Published 2 months ago
              span.time 10 min read
              span.comment
                a href="#"  23 comments
            .intro Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies...
            a.more-link href="blog-post.html"  Read more →
      /! //media-body
      /! //media
      /! //item
      .item
        .media
          = image_tag "blog/blog-post-thumb-6.jpg", title: "", alt: "image", class: "mr-3 img-fluid post-thumb d-none d-md-flex"
          .media-body
            h3.title.mb-1
              a href="blog-post.html"  About Remote Working
            .meta.mb-1
              span.date Published 3 months ago
              span.time 2 min read
              span.comment
                a href="#"  1 comment
            .intro Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies...
            a.more-link href="blog-post.html"  Read more →
      /! //media-body
      /! //media
      /! //item
      nav.blog-nav.nav.nav-justified.my-5
        a.nav-link-prev.nav-item.nav-link.d-none.rounded-left href="#"
          | Previous
          i.arrow-prev.fas.fa-long-arrow-alt-left
        a.nav-link-next.nav-item.nav-link.rounded href="blog-list.html"
          | Next
          i.arrow-next.fas.fa-long-arrow-alt-right
  / footer.footer.text-center.py-2.theme-bg-dark
  /   /! /* This template is released under the Creative Commons Attribution 3.0 License. Please keep the attribution link below when using for your own project. Thank you for your support. :) If you'd like to use the template without the attribution, you can buy the commercial license via our website: themes.3rdwavemedia.com */
  /   small.copyright
  /     | Designed with
  /     i.fas.fa-heart style=("color: #fb866a;")
  /     | by
  /     a href="http://themes.3rdwavemedia.com" target="_blank"  Xiaoying Riley
  /     | for developers

  /       /! //main-wrapper