config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /en|uk|ru/ do
    root to: 'home#show'
    get 'index.html', to: 'home#show'
    get 'about', to: 'home#about'
    get 'blog-list', to: 'post#index'
    get 'blog-post', to: 'post#show'

    namespace :admin do
      root to: 'home#show'
      resources :posts do
        delete :destroy_image, on: :member
      end
    end
    # devise_for :users,
    #           path_names: {sign_in: 'login',
    #                        sign_out: 'logout',
    #                        password: 'secret',
    #                        sign_up: 'registration'},
    #           controllers: {sessions: 'users/sessions',
    #                         registrations: 'users/registrations',
    #                         passwords: 'users/passwords',
    #                         confirmations: 'users/confirmations',
    #                         unlocks: 'users/unlocks',
    #           }
    devise_for :users, skip: %i[sessions registrations passwords confirmations unlock]
    as :user do
      get 'login.html', to: 'users/sessions#new', as: :new_user_session
      post 'login.html', to: 'users/sessions#create', as: :user_session
      match 'logout.html', to: 'users/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via

      get 'registration.html', to: 'users/registrations#new', as: :new_user_registration
      post 'registration.html', to: 'users/registrations#create', as: :user_registration
      get 'edit-registration.html', to: 'users/registrations#edit', as: :edit_user_registration
      patch 'registration.html', to: 'users/registrations#update', as: :patch_user_registration
      delete 'registration.html', to: 'users/registrations#destroy', as: :delete_user_registration
      delete 'remove-avatar/:id', to: 'users/registrations#destroy_avatar', as: :delete_user_avatar_registration

      get 'recover-password.html', to: 'users/passwords#new', as: :new_user_password
      post 'recover-password.html', to: 'users/passwords#create'
      get 'edit-recover-password.html', to: 'users/passwords#edit', as: :edit_user_password
      patch 'recover-password.html', to: 'users/passwords#update', as: :user_password
      put 'recover-password.html', to: 'users/passwords#update'

      get 'confirmation.html', to: 'users/confirmations#new', as: :new_user_confirmation
      get 'show-confirmation.html', to: 'users/confirmations#show', as: :user_confirmation
      post 'show-confirmation.html', to: 'users/confirmations#create'

      get 'unlock.html', to: 'users/unlocks#new', as: :new_user_unlock
      get 'show-unlock.html', to: 'users/unlocks#show', as: :user_unlock
      post 'show-unlock.html', to: 'users/unlocks#create'
    end

    # match '*a', to: 'admin/errors#not_found', via: :all unless Rails.env.development?
    # match '*a', to: 'admin/errors#not_found', via: :all
  end
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  has_one_attached :image
end

app/controllers/admin/posts_controller.rb
# frozen_string_literal: true

class Admin::PostsController < Admin::BaseController
  before_action :post, only: %i[show edit update destroy destroy_image]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to admin_posts_path
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to admin_posts_path
    else
      render :edit
    end
  end

  def destroy
    flash[:error] = @post.errors.full_messages unless @post.destroy
    redirect_to admin_posts_path
  end

  def destroy_image
    image = ActiveStorage::Attachment.find_by(record_id: params[:id])
    image.purge
    redirect_to edit_admin_post_path(@post)
  end

  private

  def post
    @post ||= Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :article, :time, :image)
  end
end

app/controllers/post_controller.rb
# frozen_string_literal: true

class PostController < BaseController
  def index
  end

  def show
  end
end

app/views/admin/posts/_form.html.slim
= f.error_notification
= f.input :image,
        placeholder: t('activerecord.models.post.attributes.image.placeholder'),
        required: true,
        label: t('activerecord.models.post.attributes.image.placeholder'),
        wrapper: :horizontal_file

= f.input :title,
        placeholder: t('activerecord.models.post.attributes.title.placeholder'),
        required: true,
        label: t('activerecord.models.post.attributes.title.placeholder'),
        wrapper: :horizontal_form

= f.input :intro,
        placeholder: t('activerecord.models.post.attributes.intro.placeholder'),
        required: true,
        label: t('activerecord.models.post.attributes.intro.placeholder'),
        wrapper: :horizontal_form

= f.input :article,
        placeholder: t('activerecord.models.post.attributes.article.placeholder'),
        required: true,
        label: t('activerecord.models.post.attributes.article.placeholder'),
        wrapper: :horizontal_form

= f.input :time,
        placeholder: t('activerecord.models.post.attributes.time.placeholder'),
        required: true,
        label: t('activerecord.models.post.attributes.time.placeholder'),
        wrapper: :horizontal_form

app/views/admin/posts/edit.html.slim
= content_for(:title, t('admin.photos.edit work collection'))
= simple_form_for [:admin, @post] do |f|
  /! Main content
  .content
    .container-fluid
      /! /.container-fluid
      /! /.content
      .row
        .col-md-8
          .card.card-yellow
            .card-header
              = t('admin.posts.edit post')
            .card-body
              - if @post.image.attached?
                div style=("border: 1px solid #28A745; padding: 2px")
                  = image_tag @post.image.variant(resize: '200'), alt: @post.title
                = t('remove photo')
                |  #{link_to t('do it'), destroy_image_admin_post_path(@post), method: :delete}
                p
              - else
                p style=("border: 1px solid #28A745; padding: 2px")
                  = image_tag 'backend/default-image.jpg', size: 200, alt: 'Photo Image'
              = render partial: 'form', locals: {f: f}
            .card-footer
              = link_to  admin_posts_path, class: 'btn btn-danger'
                = t(:cancel)
              = f.submit t(:save), class: 'btn btn-success pull-right'

app/views/admin/posts/index.html.slim
= content_for(:title, t('admin.posts.list of posts'))
/! Main content
.content
  .container-fluid
    /! /.container-fluid
    /! /.content
    .row
      .col-md-6.col-md-offset-10
        = link_to new_admin_post_path, class: 'btn btn-success pull-right'
          i.fas.fa-plus
          |
          = t('admin.posts.add new post')
    .row
      p

    .row
      .col-12
        .card.card-blue
          .card-header
            h3.card-title
              = t('admin.posts.post')
          /! /.card-header
          .card-body.p-0
            table.table.table-condensed
              thead
                tr
                  th style=("width: 50px")
                    = t('activerecord.models.post.attributes.title.placeholder')
                  th style=("width: 30px")
                    = t('image')
                  th
                    = t('activerecord.models.post.attributes.intro.placeholder')
                  th style=("width: 15px")
                    = t('action')

              tbody
                - @posts.each do |post|
                  tr
                    td
                      = post.title
                    td
                      - if post.image.attached?
                        = link_to admin_posts_path(post)
                          = image_tag post.image.variant(resize: '50'), alt: post.title
                            = post.title
                      - else
                        = link_to admin_post_path(post)
                          = image_tag 'backend/default-image.jpg', size: 50, alt: 'Image'
                    td
                      = post.intro
                    td
                      .btn-row
                        = link_to raw('<i class="far fa-edit"></i>'), edit_admin_post_path(post),
                                class: 'btn btn-sm btn-warning',
                                style: 'margin-right: 10px',
                                title: t('edit')
                        = link_to raw('<i class="far fa-trash-alt"></i>'), admin_post_path(post),
                                class: 'btn btn-sm btn-warning',
                                method: :delete,
                                data: {confirm: t('confirm')},
                                title: t('remove')
          /! /.card-body

app/views/admin/posts/new.html.slim
= content_for(:title, t('admin.posts.add new post'))
= simple_form_for [:admin, @post] do |f|
  /! Main content
  .content
    .container-fluid
      /! /.container-fluid
      /! /.content
      .row
        .col-md-8
          .card.card-blue
            .card-header
              = t('admin.posts.add new post')
            .card-body
              = render partial: 'form', locals: {f: f}
            .card-footer
              = link_to  admin_posts_path, class: 'btn btn-danger'
                = t(:cancel)
              = f.submit t(:save), class: 'btn btn-success pull-right'