config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /en|uk|ru/ do
    root to: 'home#show'
    get 'index.html', to: 'home#show'
    get 'about', to: 'home#about'
    get 'blog-list', to: 'post#index'
    get 'blog-post', to: 'post#show'

    namespace :admin do
      root to: 'home#show'
      resources :posts do
        delete :destroy_image, on: :member
      end
    end
    # devise_for :users,
    #           path_names: {sign_in: 'login',
    #                        sign_out: 'logout',
    #                        password: 'secret',
    #                        sign_up: 'registration'},
    #           controllers: {sessions: 'users/sessions',
    #                         registrations: 'users/registrations',
    #                         passwords: 'users/passwords',
    #                         confirmations: 'users/confirmations',
    #                         unlocks: 'users/unlocks',
    #           }
    devise_for :users, skip: %i[sessions registrations passwords confirmations unlock]
    as :user do
      get 'login.html', to: 'users/sessions#new', as: :new_user_session
      post 'login.html', to: 'users/sessions#create', as: :user_session
      match 'logout.html', to: 'users/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via

      get 'registration.html', to: 'users/registrations#new', as: :new_user_registration
      post 'registration.html', to: 'users/registrations#create', as: :user_registration
      get 'edit-registration.html', to: 'users/registrations#edit', as: :edit_user_registration
      patch 'registration.html', to: 'users/registrations#update', as: :patch_user_registration
      delete 'registration.html', to: 'users/registrations#destroy', as: :delete_user_registration
      delete 'remove-avatar/:id', to: 'users/registrations#destroy_avatar', as: :delete_user_avatar_registration

      get 'recover-password.html', to: 'users/passwords#new', as: :new_user_password
      post 'recover-password.html', to: 'users/passwords#create'
      get 'edit-recover-password.html', to: 'users/passwords#edit', as: :edit_user_password
      patch 'recover-password.html', to: 'users/passwords#update', as: :user_password
      put 'recover-password.html', to: 'users/passwords#update'

      get 'confirmation.html', to: 'users/confirmations#new', as: :new_user_confirmation
      get 'show-confirmation.html', to: 'users/confirmations#show', as: :user_confirmation
      post 'show-confirmation.html', to: 'users/confirmations#create'

      get 'unlock.html', to: 'users/unlocks#new', as: :new_user_unlock
      get 'show-unlock.html', to: 'users/unlocks#show', as: :user_unlock
      post 'show-unlock.html', to: 'users/unlocks#create'
    end

    # match '*a', to: 'admin/errors#not_found', via: :all unless Rails.env.development?
    # match '*a', to: 'admin/errors#not_found', via: :all
  end
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/shared/_content_header.html.slim
/! Content Header (Page header)
.content-header
  .container-fluid
    .row.mb-2
      .col-sm-6
        h1.m-0.text-dark
          = content_for?(:title) ? yield(:title) : Rails.application.credentials[Rails.env.to_sym][:site_title]
      /! /.col
      .col-sm-6
        ol.breadcrumb.float-sm-right
          li.breadcrumb-item
            a[href="#"]
              = t('admin.home')
          li.breadcrumb-item.active
            = content_for?(:title) ? yield(:title) : Rails.application.credentials[Rails.env.to_sym][:site_title]
    = render partial: 'admin/shared/flash'
    /! /.col
    /! /.row
    /! /.container-fluid
    /! /.content-header

app/views/admin/shared/_flash.html.slim
/ p.notice= notice
/ p.alert= alert
.row.mb-2
  .col-sm-12
    - flash.each do |key, message|
      div class="#{flash_class(key)}"
        = message

app/views/admin/shared/_foot.html.erb
<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
  <!--  <script src="plugins/jquery/jquery.min.js"></script>-->
<!-- Bootstrap -->
  <!--  <script src="plugins/bootstrap/js/bootstrap.bundle.min.js"></script>-->
<!-- AdminLTE -->
<!--  <script src="dist/js/adminlte.js"></script>-->

<!-- OPTIONAL SCRIPTS -->
<!--<script src="plugins/chart.js/Chart.min.js"></script>-->
  <!--<script src="dist/js/demo.js"></script>-->
  <!--<script src="dist/js/pages/dashboard3.js"></script>-->

app/views/admin/shared/_footer.html.slim
footer.main-footer
  strong
    | Copyright © 2014-2019
    / = succeed "." do
      a href="http://adminlte.io"  AdminLTE.io
  | All rights reserved.
  .float-right.d-none.d-sm-inline-block
    b Version
    | 3.0.2-pre
/! Control Sidebar
aside.control-sidebar.control-sidebar-dark
  /! Control sidebar content goes here
/! /.control-sidebar

app/views/admin/shared/_head.html.slim
head
  meta[charset="utf-8"]
  meta[name="viewport" content="width=device-width, initial-scale=1"]
  meta[http-equiv="x-ua-compatible" content="ie=edge"]
  title
    | AdminLTE 3 | Dashboard 3
  / link[rel="stylesheet" href="plugins/fontawesome-free/css/all.min.css"]
  link[rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"]
  / link[rel="stylesheet" href="dist/css/adminlte.min.css"]
  link[href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet"]

app/views/admin/shared/_header.html.slim
/! Navbar
nav.main-header.navbar.navbar-expand.navbar-white.navbar-light
  /! Left navbar links
  ul.navbar-nav
    li.nav-item
      a.nav-link data-widget="pushmenu" href="#"
        i.fas.fa-bars
    li.nav-item.d-none.d-sm-inline-block
      a.nav-link href="index3.html"  Home
    li.nav-item.d-none.d-sm-inline-block
      a.nav-link href="#"  Contact
    li.nav-item.d-none.d-sm-inline-block
      / a.nav-link href="#"  User
      = link_to edit_user_registration_path, class: 'nav-link'
        = current_user.email
    li.nav-item.d-none.d-sm-inline-block
      / a.nav-link href="#"  Logout
      = link_to destroy_user_session_path, method: :delete, class: 'nav-link'
        = t('devise.custom.log out')
  /! SEARCH FORM
  form.form-inline.ml-3
    .input-group.input-group-sm
      input.form-control.form-control-navbar aria-label="Search" placeholder="Search" type="search" /
      .input-group-append
        button.btn.btn-navbar type="submit"
          i.fas.fa-search
  /! Right navbar links
  ul.navbar-nav.ml-auto
    /! Messages Dropdown Menu
    li.nav-item.dropdown
      a.nav-link data-toggle="dropdown" href="#"
        i.far.fa-comments
        span.badge.badge-danger.navbar-badge 3
      .dropdown-menu.dropdown-menu-lg.dropdown-menu-right
        a.dropdown-item href="#"
          /! Message Start
          .media
            = image_tag 'backend/user1-128x128.jpg', alt: 'User Avatar', class: 'img-size-50 mr-3 img-circle'
            .media-body
              h3.dropdown-item-title
                | Brad Diesel
                span.float-right.text-sm.text-danger
                  i.fas.fa-star
              p.text-sm Call me whenever you can...
              p.text-sm.text-muted
                i.far.fa-clock.mr-1
                | 4 Hours Ago
        /! Message End
        .dropdown-divider
        a.dropdown-item href="#"
          /! Message Start
          .media
            = image_tag 'backend/user8-128x128.jpg', alt: 'User Avatar', class: 'img-size-50 mr-3 img-circle'
            .media-body
              h3.dropdown-item-title
                | John Pierce
                span.float-right.text-sm.text-muted
                  i.fas.fa-star
              p.text-sm I got your message bro
              p.text-sm.text-muted
                i.far.fa-clock.mr-1
                | 4 Hours Ago
        /! Message End
        .dropdown-divider
        a.dropdown-item href="#"
          /! Message Start
          .media
            = image_tag 'backend/user3-128x128.jpg', alt: 'User Avatar', class: 'img-size-50 mr-3 img-circle'
            .media-body
              h3.dropdown-item-title
                | Nora Silvester
                span.float-right.text-sm.text-warning
                  i.fas.fa-star
              p.text-sm The subject goes here
              p.text-sm.text-muted
                i.far.fa-clock.mr-1
                | 4 Hours Ago
        /! Message End
        .dropdown-divider
        a.dropdown-item.dropdown-footer href="#"  See All Messages
    /! Notifications Dropdown Menu
    li.nav-item.dropdown
      a.nav-link data-toggle="dropdown" href="#"
        i.far.fa-bell
        span.badge.badge-warning.navbar-badge 15
      .dropdown-menu.dropdown-menu-lg.dropdown-menu-right
        span.dropdown-item.dropdown-header 15 Notifications
        .dropdown-divider
        a.dropdown-item href="#"
          i.fas.fa-envelope.mr-2
          | 4 new messages
          span.float-right.text-muted.text-sm 3 mins
        .dropdown-divider
        a.dropdown-item href="#"
          i.fas.fa-users.mr-2
          | 8 friend requests
          span.float-right.text-muted.text-sm 12 hours
        .dropdown-divider
        a.dropdown-item href="#"
          i.fas.fa-file.mr-2
          | 3 new reports
          span.float-right.text-muted.text-sm 2 days
        .dropdown-divider
        a.dropdown-item.dropdown-footer href="#"  See All Notifications
    li.nav-item
      a.nav-link data-slide="true" data-widget="control-sidebar" href="#"
        i.fas.fa-th-large
          /! /.navbar

app/views/admin/shared/_sidebar.html.slim
/! Main Sidebar Container
aside.main-sidebar.sidebar-dark-primary.elevation-4
  /! Brand Logo
  a.brand-link[href="index3.html"]
    = image_tag 'backend/AdminLTELogo.png', alt: 'AdminLTE Logo', style: "opacity: .8", class: 'brand-image img-circle elevation-3'
    span.brand-text.font-weight-light
      | AdminLTE 3
  /! Sidebar
  .sidebar
    /! Sidebar user panel (optional)
    .user-panel.mt-3.pb-3.mb-3.d-flex
      .image
        - if current_user.avatar.attached?
          = image_tag current_user.avatar.variant(resize: "160x160"), alt: 'User Image', class: 'img-circle elevation-2'
        - else
          = image_tag 'backend/default-avatar.png', alt: 'User Image', class: 'img-circle elevation-2'
      .info
        - if current_user.username.present?
          = link_to edit_user_registration_path, class: 'd-block'
            = current_user.username
        - else
          = link_to edit_user_registration_path, class: 'd-block'
            = current_user.email
      = link_to destroy_user_session_path, method: :delete
        i.nav-icon
          span.right.badge.badge-danger
            = t('devise.custom.log out')
    /! Sidebar Menu
    nav.mt-2
      ul.nav.nav-pills.nav-sidebar.flex-column[data-widget="treeview" role="menu" data-accordion="false"]
        /!
          | Add icons to the links using the .nav-icon class
          | with font-awesome or any other icon font library
          | EXAMPLES
        li.nav-item
          = link_to admin_posts_path, class: 'nav-link'
            i.nav-icon.far.fa-image
            p
              = t('admin.posts.list of posts')
/! /.sidebar-menu
/! /.sidebar